repos:
  - repo: local
    hooks:
      - id: deadnix
        name: deadnix
        entry: deadnix --edit --fail
        language: system
        files: \.nix$
        exclude: (generated\.nix)
      - id: nixfmt
        name: nixfmt
        entry: nixfmt
        language: system
        files: \.nix$
        exclude: (generated\.nix)
      - id: statix
        name: statix
        entry: statix check --format errfmt
        language: system
        files: \.nix$
        exclude: (generated\.nix)
